apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: tetragon-prevent-escape
  namespace: kube-system
spec:
  kprobes:
    - call: "sys_execve"
      syscall: true
      args:
        - index: 0
          type: "string"
      selectors:
        - matchArgs:
            - index: 0
              operator: "Prefix"
              values:
                - "/bin/nc"
                - "/usr/bin/nsenter"
          matchActions:
            - action: Sigkill
